name: Pull request
on:
  - pull_request
  - push
jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: 'Install npm'
        run: npm ci
        working-directory: ./nodejs

      - name: 'Build package'
        run: npm run build
        working-directory: ./nodejs

      - name: 'Run tests'
        run: npm run test
        working-directory: ./nodejs

